name: fl_form
description: FormField Flutter for Text, Date, Time, Date&Time, Boolean, Avatar, Item Picker, Radio Button, Checkbox group.
version: 0.5.3
homepage: https://github.com/dangngocduc/fl_form

environment:
  sdk: ^3.8.1

dependencies:
  async: ^2.13.0
  calendar_date_picker2: ^2.0.1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: any
  stream_transform: ^2.1.1
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

